name: Python Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["master", "main"]
    paths:
      - "src/battleship/**.py"
      - "tests/**.py"
      - ".coveragerc.toml"
      - ".pytest.toml"
      - ".ruff.toml"
      - "pyproject.toml"
      - "ty.toml"
      - "uv.lock"
      - ".github/workflows/python-test.yml"

  push:
    branches: ["master", "main"]
    paths:
      - "src/battleship/**.py"
      - "tests/**.py"
      - ".coveragerc.toml"
      - ".pytest.toml"
      - ".ruff.toml"
      - "pyproject.toml"
      - "ty.toml"
      - "uv.lock"
      - ".github/workflows/**"

permissions:
  contents: write
  statuses: write

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: true
          submodules: false

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          python-version: "3.14"
          working-directory: "."
          enable-cache: true
          cache-dependency-glob: |
            **/.coveragerc.toml
            **/.pytest.toml
            **/pyproject.toml
            **/uv.lock

      - name: Install deps
        run: uv sync --all-groups

      - name: Run PyTest
        run: |
          uv run pytest
